let productos = [
  { nombre: "JOGGIN", tipoProductoId: 1 },
  { nombre: "PANTALON DE VESTIR" , tipoProductoId: 1},
  { nombre: "JEAN", tipoProductoId: 1 },
  { nombre: "CALZAS/LEGGINS" , tipoProductoId: 1},
  { nombre: "SHORTS", tipoProductoId: 2 },
  { nombre: "BERMUDAS" , tipoProductoId: 2},
  { nombre: "DEPORTIVOS", tipoProductoId: 2 },
  { nombre: "JEAN" , tipoProductoId: 2},
  { nombre: "SHORTS ELEGANTES", tipoProductoId: 2 },
  { nombre: "CAMISETAS MANGA CORTA", tipoProductoId: 3 },
  { nombre: "CAMISETAS MANGA LARGAimage.png", tipoProductoId: 3 },
  { nombre: "BLUSA", tipoProductoId: 3 },
  { nombre: "REMERAS MANGA CORTA", tipoProductoId: 3 },
  { nombre: "REMERAS MANGA LARGA", tipoProductoId: 3 },
  { nombre: "TOP", tipoProductoId: 3 },
  { nombre: "CHOMBA", tipoProductoId: 3 },
  { nombre: "MUSCULOSA", tipoProductoId: 3 },
  { nombre: "DEPORTIVA", tipoProductoId: 3 },
  { nombre: "CAMISA", tipoProductoId: 4 },
  { nombre: "BLAZER" , tipoProductoId: 5},
  { nombre: "SACO", tipoProductoId: 5 },
  { nombre: "CHALECO" , tipoProductoId: 5},
  { nombre: "CAMPERA" , tipoProductoId: 5},
  { nombre: "BUZO" , tipoProductoId: 5},
  { nombre: "PULOVER/SUETER" , tipoProductoId:5 },
  { nombre: "TAPADO" , tipoProductoId: 5},
  { nombre: "PILOTO" , tipoProductoId:5 },
  { nombre: "VESTIDO DE FIESTA", tipoProductoId: 6 },
  { nombre: "BLUSA" , tipoProductoId: 6},
  { nombre: "TRAJE" , tipoProductoId: 6},
  { nombre: "CAMISA", tipoProductoId: 6 },
  { nombre: "POLLERA/FALDA" , tipoProductoId: 7},
  { nombre: "MONO/ENTERITO" , tipoProductoId:7 },
  { nombre: "VESTIDOS INFORMALES" , tipoProductoId:7 },
  { nombre: "BUFANDA" , tipoProductoId:8 },
  { nombre: "PAÑUELOS", tipoProductoId: 8 },
  { nombre: "GUANTES", tipoProductoId: 8 },
  { nombre: "GORROS", tipoProductoId:8 },
];
module.exports = {
  productos,
};
