let productos = [
  { nombre: "JOGGIN", categoriumId: 1 },
  { nombre: "PANTALON DE VESTIR" , categoriumId: 1},
  { nombre: "JEAN", categoriumId: 1 },
  { nombre: "CALZAS/LEGGINS" , categoriumId: 1},
  { nombre: "SHORTS", categoriumId: 2 },
  { nombre: "BERMUDAS" , categoriumId: 2},
  { nombre: "DEPORTIVOS", categoriumId: 2 },
  { nombre: "JEAN" , categoriumId: 2},
  { nombre: "SHORTS ELEGANTES", categoriumId: 2 },
  { nombre: "CAMISETAS MANGA CORTA", categoriumId: 3 },
  { nombre: "CAMISETAS MANGA LARGA", categoriumId: 3 },
  { nombre: "BLUSA", categoriumId: 3 },
  { nombre: "REMERAS MANGA CORTA", categoriumId: 3 },
  { nombre: "REMERAS MANGA LARGA", categoriumId: 3 },
  { nombre: "TOP", categoriumId: 3 },
  { nombre: "CHOMBA", categoriumId: 3 },
  { nombre: "MUSCULOSA", categoriumId: 3 },
  { nombre: "DEPORTIVA", categoriumId: 3 },
  { nombre: "CAMISA", categoriumId: 4 },
  { nombre: "BLAZER" , categoriumId: 5},
  { nombre: "SACO", categoriumId: 5 },
  { nombre: "CHALECO" , categoriumId: 5},
  { nombre: "CAMPERA" , categoriumId: 5},
  { nombre: "BUZO" , categoriumId: 5},
  { nombre: "PULOVER/SUETER" , categoriumId:5 },
  { nombre: "TAPADO" , categoriumId: 5},
  { nombre: "PILOTO" , categoriumId:5 },
  { nombre: "VESTIDO DE FIESTA", categoriumId: 6 },
  { nombre: "BLUSA" , categoriumId: 6},
  { nombre: "TRAJE" , categoriumId: 6},
  { nombre: "CAMISA", categoriumId: 6 },
  { nombre: "POLLERA/FALDA" , categoriumId: 7},
  { nombre: "MONO/ENTERITO" , categoriumId:7 },
  { nombre: "VESTIDOS INFORMALES" , categoriumId:7 },
  { nombre: "BUFANDA" , categoriumId:8 },
  { nombre: "PAÑUELOS", categoriumId: 8 },
  { nombre: "GUANTES", categoriumId: 8 },
  { nombre: "GORROS", categoriumId:8 },
];
module.exports = {
  productos,
};
